In [1]:
import numpy as np

In [2]:
#single dimension

arr1 = np.array([1,2,3,4])

In [3]:
arr1

array([1, 2, 3, 4])

In [4]:
# 2 dimension

arr2 = np.array([[1,2,3,4],[5,6,7,8]])

In [5]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
# convert the array into float

arr = np.array([1,2,3,4],dtype = float)

In [7]:
arr

array([1., 2., 3., 4.])

In [8]:
type(arr)


numpy.ndarray

In [9]:
arr.dtype

dtype('float64')

In [10]:
# convert the array into int

arr = np.array([1., 2., 3., 4.],int)

In [11]:
arr

array([1, 2, 3, 4])

In [12]:
# array with Zeros 

arr = np.zeros(5)

In [13]:
arr

array([0., 0., 0., 0., 0.])

In [14]:
# array with one with int type

arr = np.ones(5,dtype = int)

In [15]:
arr

array([1, 1, 1, 1, 1])

In [16]:
# array with random numbers

arr = np.random.rand(5,3)

In [17]:
arr

array([[0.28631314, 0.9476801 , 0.34045781],
       [0.40540617, 0.36744064, 0.66433254],
       [0.60977898, 0.53502993, 0.24230528],
       [0.57705846, 0.28238175, 0.90536182],
       [0.06223081, 0.70967646, 0.5324502 ]])

In [18]:
# array with imatrix 
arr = np.eye(4, dtype = int)

In [19]:
arr

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [20]:
# Evenly spaced ndarray with the help of np.arange

arr = np.arange(10)

In [21]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr = np.arange(2,10,2)

In [23]:
arr

array([2, 4, 6, 8])

In [24]:
# Dimensions of array

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('array :','\n',arr)
print('dimensions :',arr.ndim)

array : 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
dimensions : 2


In [25]:
# shape of the array

arr = np.array([[1,2,3,4],[5,9,8,7]])
print('array :','\n',arr)
print('shape :',arr.shape)
print('rows :',arr.shape[0])
print('columns :',arr.shape[1])

array : 
 [[1 2 3 4]
 [5 9 8 7]]
shape : (2, 4)
rows : 2
columns : 4


In [57]:
# size of an array

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('size of an array : ',arr.size)
print('manual determination of size of array : ',arr.shape[0]*arr.shape[1])

size of an array :  10
manual determination of size of array :  10


In [77]:
# reshape a numpy array

arr = np.array([4,5,3,7,9,8])
np.reshape(arr,(3,2))

array([[4, 5],
       [3, 7],
       [9, 8]])

In [89]:
# transpose of array

arr =  np.array([[1,2,3],[4,5,6]])
b = np.transpose(arr)
print('orginal shape :',arr.shape,'\n',arr)
print('transpose shape :',b.shape,'\n',b)


orginal shape : (2, 3) 
 [[1 2 3]
 [4 5 6]]
transpose shape : (3, 2) 
 [[1 4]
 [2 5]
 [3 6]]


In [91]:
# indexing and slicing with array
# 1-dimension

a = ([4,5,6,3,7,8])
print(a[1:5:2])

[5, 3]


In [93]:
a = ([4,5,6,3,7,8])
print(a[1:6:2])

[5, 3, 8]


In [97]:
# indexing and slicing with array
# 2-dimension

arr = np.array([[1,2,3,4],[5,6,7,8]])
print('first row :',arr[0])
print('second row :',arr[1])
print('second column:',arr[:,1])


first row : [1 2 3 4]
second row : [5 6 7 8]
second column: [2 6]


In [114]:
# Basic arithmetic operators on numpy
arr = np.array([1,2,3,4,5,6])
print('subtract:',arr-5)
print('multiply:',arr* 2)
print('divide:',arr/6)
print('power:',arr** 2)
print('remainder:',arr%6)


subtract: [-4 -3 -2 -1  0  1]
multiply: [ 2  4  6  8 10 12]
divide: [0.16666667 0.33333333 0.5        0.66666667 0.83333333 1.        ]
power: [ 1  4  9 16 25 36]
remainder: [1 2 3 4 5 0]


In [116]:
# mean , median , and standard deviation
arr = np.arange(5,15,2)
print(arr)
print('mean:',np.mean(arr))
print('median:',np.median(arr))
print('standard deviation:',np.std(arr))

[ 5  7  9 11 13]
mean: 9.0
median: 9.0
standard deviation: 2.8284271247461903


In [118]:
# min and max values in numpy

arr = np.array([[1,2,3],[4,5,6]])
print('min:',np.min(arr,axis = 0))
print('max:',np.max(arr,axis = 1))


min: [1 2 3]
max: [3 6]
